class AmeliaBedelia
  def draw_the_drapes
    puts "
    ............................---------------.......
    .....//+++oyyooyso/+ys//+os+++os//+oo//++o//-/-...
    ......-/+++hyoohyo/oho///:s+//os///os///+s//......
    ......-/+++yy+oyyo/yy//+--s+//os///os///+s/:......
    ......-/+/+yy+oyyo+yo/o:`-s+//os/:/os/:/+o/:......
    ......-:+/oyy/oyy+sy/o/.`-s+//os/::+o/::+o/:......
    ......-:+/oyy/yys+yoo+-``-s/:/os/::+o/::/o/:......
    ......--+/oys/hyooyos:```:o/:/os/::+o/::/o/:......
    ......--+/oys+dy+yos/.```:o/:/os:::+o/::/o/:......
    ......--+/oyood+osy+-````/o/:/os:::+o/::/o/:......
    ......--++sy+ys+yyo:`````/o/:/ss:::+o/::/o/:......
    ......--++sy+y+syo/.`````/o///so:::+o/::/o/:......
    ......--+osss+syo+-``````/o///ss/::+o/::/o/:......
    ......--+osoooso+.```````/o///ss/::oo/::/o+:......
    ......--/oooso+/.````````/o///ss//:oo//:/o+/......
    .......-/oo+:-.``````````/o///ss///oo///+o+/......
    .......-+so/`````````````/o//+ss///oo///+s+/-.....
    .......-+yo+-`````.``````/o//+ss///oo///+s+/-.....
    .......-oyoo:............/o+/+ss+/+so///+s++-.....
    .......-sy+o/-.........../o+++ss+/+so/++os++-.....
    .......-hs+s+-.........../o++oys+++so+++oso+-.....
    .......:hs+yo:...........+o++oys+++so+++osoo-`````
    ......-+ys+so:-..........oo++oss+++so++oosoo:.....
    -------:/::--------------://::::::::/:::::::------
    "
  end
end

class Person
  def draw_the_drapes
    puts "The drapes are now closed."
  end
end

class PartyPlanner
  def set_up_for_party(person)
    person.draw_the_drapes
  end
end

amelia = AmeliaBedelia.new
walter = Person.new
sean = PartyPlanner.new

sean.set_up_for_party(walter)

sean.set_up_for_party(amelia)
